### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by LucPestille** [flokosiol/kirby-subpagelist#2]
One thing I can see as being useful in the future is pagination when the list gets longer than a certain (user definable) point. Bonus points for AJAX updating of the list as you page through...

**Comment by flokosiol** [comment]
Thanks for your suggestion. I think it should be implemented the same way as the [subpage limit page setting](http://getkirby.com/docs/panel/blueprints/subpages-settings#limit-displayed-subpages). I will have a look at this.
