### ISSUE TITLE
Compatibility with KIRBY 2.2.1

### ISSUE THREAD

**Issue by helllicht** [flokosiol/kirby-subpagelist#3]
We found this issue using the new kirby version:

Fatal error: Class 'Snippet' not found in …/site/fields/subpagelist/subpagelist.php on line 74

Will there be an update for 2.2.1?

**Comment by flokosiol** [comment]
Yes, there will be an update and I hope I can release it until tomorrow ;-)

**Comment by flokosiol** [comment]
Please checkout the [develop](https://github.com/flokosiol/kirby-subpagelist/tree/develop) branch to get the latest version of the plugin. It should work with Kirby 2.2. It would be nice if you could let me know if everything works as expected. After some more testing I will merge it to the master branch.

Greetings, Flo.

**Comment by jensfranke** [comment]
Thanks for the update. The new version in the dev-branch works fine except the title »Seiten/Page«.

![bildschirmfoto 2015-11-21 um 16 47 39](https://cloud.githubusercontent.com/assets/595504/11319212/a4ef1dda-906f-11e5-8561-3b7ee31d66b8.png)

**Comment by jensfranke** [comment]
thanks @flokosiol for the fix!
